### ISSUE TITLE
Simplify dockerization

### ISSUE THREAD

**Issue by eddie-knight** [ossf/si-tooling#4]
- Are there any defaults we can use to reduce the number of required values?
- Are there any values in the example that we can shorten? 
- Can we publish the image so that users don't need to build it locally?

**Comment by luigigubello** [comment]
Can we close this? @eddie-knight

**Comment by eddie-knight** [comment]
@luigigubello Do we want to publish the image (ie, to Docker Hub)?

**Comment by luigigubello** [comment]
@eddie-knight here we go :) https://hub.docker.com/r/luigigubello/security-insights-validator

**Comment by eddie-knight** [comment]
Slick. We can cross the namespace issue later
